//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatHistory
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Msg { get; set; }
        public System.DateTime AddDate { get; set; }
        public byte isRead { get; set; }
        public int MsgType { get; set; }
        public int ChatGroupId { get; set; }
    }
}
